export const orders = [{
    rowId: 1,
    orderId: "CA-2013-152156",
    orderDate: "11/9/13",
    shipDate: "11/12/13",
    shipMode: "Second Class",
    customerId: "CG-12520",
    customerName: "Claire Gute",
    segment: "Consumer",
    country: "United States",
    city: "Henderson",
    state: "Kentucky",
    postalCode: 42420,
    region: "South",
    productId: "FUR-BO-10001798",
    category: "Furniture",
    subCategory: "Bookcases",
    productName: "Bush Somerset Collection Bookcase",
    sales: 261.96,
    quantity: 2,
    discount: 0,
    profit: 41.96,
    status: "Complete"
  },
  {
    rowId: 2,
    orderId: "CA-2013-152156",
    orderDate: "11/9/13",
    shipDate: "11/12/13",
    shipMode: "Second Class",
    customerId: "CG-12520",
    customerName: "Claire Gute",
    segment: "Consumer",
    country: "United States",
    city: "Henderson",
    state: "Kentucky",
    postalCode: 42420,
    region: "South",
    productId: "FUR-CH-10000454",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",
    sales: 731.94,
    quantity: 3,
    discount: 0,
    profit: 219.52,
    status: "Complete"
  },
  {
    rowId: 3,
    orderId: "CA-2013-138688",
    orderDate: "6/13/13",
    shipDate: "6/17/13",
    shipMode: "Second Class",
    customerId: "DV-13045",
    customerName: "Darrin Van Huff",
    segment: "Corporate",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90036,
    region: "West",
    productId: "OFF-LA-10000240",
    category: "Office Supplies",
    subCategory: "Labels",
    productName: "Self-Adhesive Address Labels for Typewriters by Universal",
    sales: 14.62,
    quantity: 2,
    discount: 0,
    profit: 6.87,
    status: "Pending"
  },
  {
    rowId: 4,
    orderId: "US-2012-108966",
    orderDate: "10/11/12",
    shipDate: "10/18/12",
    shipMode: "Standard Class",
    customerId: "SO-20335",
    customerName: "Sean O'Donnell",
    segment: "Consumer",
    country: "United States",
    city: "Fort Lauderdale",
    state: "Florida",
    postalCode: 33311,
    region: "South",
    productId: "FUR-TA-10000577",
    category: "Furniture",
    subCategory: "Tables",
    productName: "Bretford CR4500 Series Slim Rectangular Table",
    sales: 957.57,
    quantity: 5,
    discount: 0.45,
    profit: -383.51,
    status: "Pending"
  },
  {
    rowId: 5,
    orderId: "US-2012-108966",
    orderDate: "10/11/12",
    shipDate: "10/18/12",
    shipMode: "Standard Class",
    customerId: "SO-20335",
    customerName: "Sean O'Donnell",
    segment: "Consumer",
    country: "United States",
    city: "Fort Lauderdale",
    state: "Florida",
    postalCode: 33311,
    region: "South",
    productId: "OFF-ST-10000760",
    category: "Office Supplies",
    subCategory: "Storage",
    productName: "Eldon Fold 'N Roll Cart System",
    sales: 22.38,
    quantity: 2,
    discount: 0.2,
    profit: 2.54,
    status: "Pending"
  },
  {
    rowId: 6,
    orderId: "CA-2011-115812",
    orderDate: "6/9/11",
    shipDate: "6/14/11",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "FUR-FU-10001487",
    category: "Furniture",
    subCategory: "Furnishings",
    productName: "Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood",
    sales: 48.86,
    quantity: 7,
    discount: 0,
    profit: 14.16,
    status: "Pending"
  },
  {
    rowId: 7,
    orderId: "CA-2011-115812",
    orderDate: "6/9/11",
    shipDate: "6/14/11",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "OFF-AR-10002833",
    category: "Office Supplies",
    subCategory: "Art",
    productName: "Newell 322",
    sales: 7.28,
    quantity: 4,
    discount: 0,
    profit: 1.96,
    status: "Pending"
  },
  {
    rowId: 8,
    orderId: "CA-2011-115812",
    orderDate: "6/9/11",
    shipDate: "6/14/11",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "TEC-PH-10002275",
    category: "Technology",
    subCategory: "Phones",
    productName: "Mitel 5320 IP Phone VoIP phone",
    sales: 907.12,
    quantity: 6,
    discount: 0.2,
    profit: 90.72,
    status: "Pending"
  },
  {
    rowId: 9,
    orderId: "CA-2011-115812",
    orderDate: "6/9/11",
    shipDate: "6/14/11",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "OFF-BI-10003910",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "DXL Angle-View Binders with Locking Rings by Samsill",
    sales: 18.54,
    quantity: 3,
    discount: 0.2,
    profit: 5.25,
    status: "Complete"
  },
  {
    rowId: 10,
    orderId: "CA-2011-115812",
    orderDate: "6/9/11",
    shipDate: "6/14/11",
    shipMode: "Standard Class",
    customerId: "BH-11710",
    customerName: "Brosina Hoffman",
    segment: "Consumer",
    country: "United States",
    city: "Los Angeles",
    state: "California",
    postalCode: 90032,
    region: "West",
    productId: "OFF-AP-10002892",
    category: "Office Supplies",
    subCategory: "Appliances",
    productName: "Belkin F5C206VTEL 6 Outlet Surge",
    sales: 114.92,
    quantity: 5,
    discount: 0,
    profit: 34.47,
    status: "Complete"
  }
]


export const inventory = [{
    rowId: 1,
    segment: "Consumer",
    productId: "FUR-BO-10001798",
    category: "Furniture",
    subCategory: "Bookcases",
    productName: "Bush Somerset Collection Bookcase",
    price: 132.90,
    inStock: 55,
    stockLevel: 'High'
  },
  {
    rowId: 2,
    segment: "Consumer",
    productId: "FUR-CH-10000454",
    category: "Furniture",
    subCategory: "Chairs",
    productName: "Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",
    price: 731.94,
    inStock: 344,
    stockLevel: 'High'


  },
  {
    rowId: 3,
    segment: "Corporate",
    productId: "OFF-LA-10000240",
    category: "Office Supplies",
    subCategory: "Labels",
    productName: "Self-Adhesive Address Labels for Typewriters by Universal",
    price: 14.62,
    inStock: 2,
    stockLevel: 'Low'


  },
  {
    rowId: 4,
    segment: "Consumer",
    productId: "FUR-TA-10000577",
    category: "Furniture",
    subCategory: "Tables",
    productName: "Bretford CR4500 Series Slim Rectangular Table",
    price: 957.5775,
    inStock: 5,
    stockLevel: 'High'

  },
  {
    rowId: 5,
    segment: "Consumer",
    productId: "OFF-ST-10000760",
    category: "Office Supplies",
    subCategory: "Storage",
    productName: "Eldon Fold 'N Roll Cart System",
    price: 11.68,
    inStock: 605,
    stockLevel: 'Low'

  },
  {
    rowId: 6,
    segment: "Consumer",
    productId: "FUR-FU-10001487",
    category: "Furniture",
    subCategory: "Furnishings",
    productName: "Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood",
    price: 6.86,
    inStock: 700,
    stockLevel: 'High'

  },
  {
    rowId: 7,
    segment: "Consumer",
    productId: "OFF-AR-10002833",
    category: "Office Supplies",
    subCategory: "Art",
    productName: "Newell 322",
    price: 1.28,
    inStock: 865,
    stockLevel: 'High'


  },
  {
    rowId: 8,
    segment: "Consumer",
    productId: "TEC-PH-10002275",
    category: "Technology",
    subCategory: "Phones",
    productName: "Mitel 5320 IP Phone VoIP phone",
    price: 127.152,
    inStock: 69,
    stockLevel: 'Mid'


  },
  {
    rowId: 9,
    segment: "Consumer",
    productId: "OFF-BI-10003910",
    category: "Office Supplies",
    subCategory: "Binders",
    productName: "DXL Angle-View Binders with Locking Rings by Samsill",
    price: 8.50,
    inStock: 433,
    stockLevel: 'High'

  },
  {
    rowId: 10,
    segment: "Consumer",
    productId: "OFF-AP-10002892",
    category: "Office Supplies",
    subCategory: "Appliances",
    productName: "Belkin F5C206VTEL 6 Outlet Surge",
    price: 24.90,
    inStock: 399,
    stockLevel: 'Low'

  }
]